# Завдання №1 "Створення та інспектування np-массивів"

## Завдання №1.1

In [1]:
import numpy as np

arr1_1 = np.array([[1.2, 2.3, 3.4, 4.5],
                   [5.6, 6.7, 7.8, 8.9],
                   [9.0, 10.1, 11.2, 12.3]])

np.info(arr1_1)

class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x18e919f51c0
byteorder:  little
byteswap:  False
type: float64


In [2]:
import numpy as np

arr1_1 = np.array([[1.2, 2.3, 3.4, 4.5],
                   [5.6, 6.7, 7.8, 8.9],
                   [9.0, 10.1, 11.2, 12.3]])
print(arr1_1)

[[ 1.2  2.3  3.4  4.5]
 [ 5.6  6.7  7.8  8.9]
 [ 9.  10.1 11.2 12.3]]


## Завдання №1.2

In [5]:
arr1_2 = np.array(['cat', 'dog', 'mouse', 'pig', 'cow'])

print(arr1_2)

['cat' 'dog' 'mouse' 'pig' 'cow']


## Завдання №1.3

In [6]:
arr1_3 = np.ones((3, 4), dtype=float)

print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Завдання №2 "Перетворення форми та типу массивів"

## Завдання №2.1

In [7]:
arr2_1 = np.zeros((3, 1, 3), dtype=bool)

print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


## Завдання №2.2

In [8]:
arr2_1 = np.zeros((3, 1, 3), dtype=bool)
arr2_2 = arr2_1.reshape(3, 3).astype(int)

print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Завдання №2.3

In [10]:
arr2_3 = np.arange(10, 21, 2).reshape(3, 2)

print(arr2_3)

[[10 12]
 [14 16]
 [18 20]]


# Завдання №3 "Доступ до елементів масива"

## Завдання №3.1

In [1]:
average, vidh = 55, 15
arr3_1 = np.random.normal(average, vidh, size=(4, 5))
print(arr3_1)

[[49.77763194 68.80525068 60.21102715 73.36320615 26.34207793]
 [58.99875177 67.97861416 84.64930236 34.5269781  73.32180587]
 [63.76753272 45.22699843 45.50617465 64.47608686 55.82965642]
 [62.69755179 57.82251463 44.51647927 35.78287042 34.94818066]]


## Завдання №3.2

In [25]:
el3_2 = arr3_1[1, 2]
print(el3_2)

38.69228233094594


## Завдання №3.3

In [26]:
vect3_3 = arr3_1[1]
print(vect3_3)

[60.30655444 46.13260844 38.69228233 63.95622571 56.65778682]


## Завдання №3.4

In [27]:
vect3_4 = arr3_1[:, 2]
print(vect3_4)

[52.04597924 38.69228233 36.44437493 40.35264293]


## Завдання №3.5

In [28]:
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[46.13260844 38.69228233]
 [54.52770107 36.44437493]]


# Завдання №4 "Матричні компоненти масива"

## Завдання №4.1

In [3]:
mat4_1 = np.random.randint(100, 201, size=(6, 6))
print(mat4_1)

[[128 159 106 124 113 190]
 [153 195 114 183 176 169]
 [111 110 183 117 120 123]
 [199 141 167 173 125 195]
 [131 170 180 104 149 152]
 [100 184 109 135 112 132]]


## Завдання №4.2

In [4]:
diag4_2 = [mat4_1[i][i] for i in range(len(mat4_1))]
print(diag4_2)

[128, 195, 183, 173, 149, 132]


## Завдання №4.3

In [5]:
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[128 153 111 199 131 100]
 [159 195 110 141 170 184]
 [106 114 183 167 180 109]
 [124 183 117 173 104 135]
 [113 176 120 125 149 112]
 [190 169 123 195 152 132]]


## Завдання №4.4

In [6]:
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[-1.52812273e-02 -2.35990339e-04 -2.12772264e-02  1.74713769e-02
   1.54989863e-02 -1.53295462e-03]
 [-6.58030660e-03 -6.17787268e-03 -1.19497908e-02  2.47463338e-03
   8.54440368e-03  1.50215162e-02]
 [-2.10827691e-03 -7.36198697e-03  8.66741495e-03 -7.79245020e-05
  -1.38969974e-05  4.51487873e-03]
 [-7.65974786e-04  3.50532745e-03  1.38666788e-02 -6.67684798e-04
  -1.97230918e-02  7.39122628e-03]
 [ 2.10008302e-03  1.63003048e-02  3.89559315e-03 -1.01531124e-02
   4.89799232e-03 -1.81633572e-02]
 [ 2.14916563e-02 -2.54597847e-03  8.13202909e-03 -7.32341229e-03
  -7.62508995e-03 -8.07806696e-03]]


# Завдання №5 "Операції над масивами"

## Завдання №5.1

In [2]:
mat5_1 = np.random.randint(1, 10, size=(3,4))
print("Матриця:\n", mat5_1)

Матриця:
 [[1 6 5 4]
 [8 1 4 3]
 [3 7 3 4]]


In [3]:
sum_mat5_1 = np.sum(mat5_1, axis=1)
print("Суми елементів рядків:\n", sum_mat5_1)

Суми елементів рядків:
 [16 16 17]


## Завдання №5.2

In [4]:
min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)

16


## Завдання №5.3

In [5]:
mat5_3 = mat5_1 + 100
print(mat5_3)

[[101 106 105 104]
 [108 101 104 103]
 [103 107 103 104]]


## Завдання №5.4

In [6]:
mat5_4 = np.dot(mat5_1.T, np.diag(mat5_3))
print(mat5_4)

[1218 1428 1218 1119]


## Завдання №5.5

In [7]:
mat5_5 = np.hstack((mat5_3.T, mat5_4.reshape(-1, 1)))
print(mat5_5)

[[ 101  108  103 1218]
 [ 106  101  107 1428]
 [ 105  104  103 1218]
 [ 104  103  104 1119]]


In [8]:
rank = np.linalg.matrix_rank(mat5_5)
print("Ранг матриці: ", rank)

Ранг матриці:  4
